version: "2"

services:
  db:
    image: "postgres:10-alpine"

    container_name: "victor_db"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
